project_id = "bpwjdblhcdbwwzuzcrbx"

[api]
enabled = true
port = 54321
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.record-puzzle-completion]
verify_jwt = true

[functions.record-lab-completion]
verify_jwt = true

[functions.record-project-completion]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true