// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpwjdblhcdbwwzuzcrbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwd2pkYmxoY2Rid3d6dXpjcmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDExMzAsImV4cCI6MjA3NDY3NzEzMH0.uudAugR1fptnFfdp_I0WLkAL3UOZpkroQWJV4NoBdBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});